### ISSUE TITLE
Question: How did this work? (im too lazy to read the code)

### ISSUE THREAD

**Issue by EBSmash** [NathanW-05/Desmos2.0#1]
Just curious.

**Comment by node3112** [comment]
The gist was that you would open a chest (or really any other storage block) and attempt to move into the chunk you wanted to query.
If the chunk was loaded, the chest would close, otherwise nothing would happen.

The reason for this:
1. Most Paper servers have a config option that prevents you from moving into unloaded chunks (`preventMovingIntoUnloadedChunks`), and most server owners enable this.
When you try to move into an unloaded chunk, it calls `internalTeleport()` which does not post a `PlayerTeleportEvent`.
If the chunk was loaded however, it teleports you back for "moving too quickly" and calls `a()` (`teleport()` when mapped), which does post a `PlayerTeleportEvent`.
2. NCP has a config option that closes inventories when you teleport (`nocheatplus.checks.inventory.open`), which would be triggered by this `PlayerTeleportEvent`, and hence would close the chest.

Not sure if @NathanW-05 has anything else to add (he found the NCP part of it).

**Comment by EBSmash** [comment]
Damn, that's impressive, thank you for the explanation.

**Comment by NathanW-05** [comment]
That is not accurate. He is making that up. Please don't listen to his BS.

**Comment by EBSmash** [comment]
uhh...
